### ISSUE TITLE
As a user I want to be able to upload *.jar files

### ISSUE THREAD

**Issue by paulroemer** [vaadin/vaadin-upload#204] opened 2017-08-02 10:36 UTC
As the title already explains, I am not able to use the vaadin-upload as configured below to allow uploads of .jar files:
```
        <vaadin-upload
                id="upload"
                class="my-components__upload"
                on-upload-success="onUploadSuccess"
                on-upload-abort="onUploadAbortOrError"
                on-upload-error="onUploadAbortOrError"
                max-files="1"
                nodrop target="/directory-upload"
                accept="application/zip,application/java-archive"/>
```

ZIP files work quite fine but if I select a *.jar it is silently ignored. No output on dev console nor any access to the upload request handler.

**Comment by manolo** [comment] 2017-08-09 12:29
@paulroemer use `"vaadin-upload":  "#fix/204"` in your `bower.json` until the PR with the fix is merged. Let me know if it works for you

**Comment by manolo** [comment] 2017-09-05 08:37
The [spec](https://www.w3schools.com/tags/att_input_accept.asp) in the `accept` attribute says that when specifying media type, you need to use valid types listed in [iana](http://www.iana.org/assignments/media-types/media-types.xhtml)

Apparently your case it's not a valid media type, although it could be a valid [mime-type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types) 

After researching a bit, and after proposing a patch, I see that we should not allow empty types when the user restricts the media type.
The problem is that with my patch we cover this use case, but also we allow any unknown file type to be allowed. For instance if the user sets `accept=image/png` the use could eventually select a `.jar` file.

So for your use case, you should use extensions instead of media types `accept=*.zip,*.jar`

**Closed** 2017-09-13 09:22 UTC
