### ISSUE TITLE
Weird layout with paper-icon-button on edge + IE

### ISSUE THREAD

**Issue by BorntraegerMarc** [vaadin/vaadin-upload#233] opened 2017-11-15 06:31 UTC
When I have the following code:
```
<vaadin-upload id="upload" target="/api/v0/files">
        <paper-icon-button slot="add-button" src="assets/imgs/plus-icon.png"></paper-icon-button>
        <!-- We do not want a file list.-->
        <span slot="file-list"></span>
</vaadin-upload>
```

It generates a huge area:
![image](https://user-images.githubusercontent.com/7549295/32821997-aa74c01e-c9d6-11e7-8d28-30c987f68a98.png)

And also the `paper-icon-button` is not in the middle. I need to manually style it with `bottom` and `right` for it to be in the middle.

Here's the same code on chrome:
![image](https://user-images.githubusercontent.com/7549295/32822043-e5ffee56-c9d6-11e7-901e-9851b5c37413.png)

Also note there are weird dotted lines in IE + Edge. Not in chrome + safari

**Comment by samiheikki** [comment] 2017-11-15 17:44
Can you
1) Share the icon-image url
2) Full code of the vaadin-upload, I assume you are for example using `slot="drop-label"` and `slot="drop-label-icon"` as they are missing in the images
3) Tell me which version of upload you are using.
4) And which version of Windows

I tried with following code on Win11 IE and Edge and were unable to reproduce the issue

```
<style>
  #upload {
    width: 40px;
  }
</style>
<vaadin-upload id="upload">
  <paper-icon-button slot="add-button" src="https://cdn4.iconfinder.com/data/icons/wirecons-free-vector-icons/32/add-128.png"></paper-icon-button>
  <!-- We do not want a file list.-->
  <span slot="file-list"></span>
  <span slot="drop-label"></span>
  <span slot="drop-label-icon"></span>
</vaadin-upload>
```
edge:
![upload_edge](https://user-images.githubusercontent.com/8615573/32851276-3da835d0-ca3d-11e7-9e83-aa12784e38a0.PNG)
ie11:
![upload_ie11](https://user-images.githubusercontent.com/8615573/32851277-3dcb5a92-ca3d-11e7-9c8c-ee5421601367.PNG)


PS. Upload has borders in the default style. Hide them with `border: none;`

**Comment by samiheikki** [comment] 2017-11-15 17:49
Also a fiddle of the code where the bug occurs would be awesome.

**Comment by samiheikki** [comment] 2017-11-15 17:56
Might have been fixed in here: https://github.com/vaadin/vaadin-upload/pull/226

**Comment by BorntraegerMarc** [comment] 2017-11-16 08:43
Thanks for the answer. I've published a repo: https://github.com/BorntraegerMarc/vaadin-ie (didn0t get jsfiddle to work)

Chrome:
![image](https://user-images.githubusercontent.com/7549295/32881664-3e712b32-cab2-11e7-9d3c-ccfdbecaf4e2.png)

Edge 16:
![image](https://user-images.githubusercontent.com/7549295/32881671-45d6b874-cab2-11e7-9bb7-760009b4dc3a.png)

Call me crazy but something is definitely styled differently on edge 16 😄 seems like it's way higher...

**Comment by BorntraegerMarc** [comment] 2017-11-16 08:50
But yeah... The latest master version does definitely fix something. It looks way better than with `v2.1.2`

In my latest commit https://github.com/BorntraegerMarc/vaadin-ie/commit/9e49905def05dea35181e33b72dddc13043f32e8 I added flex layout to the equation. there it becomes really obvious that edge renders it differently and it takes way more space:

![image](https://user-images.githubusercontent.com/7549295/32882109-8bb0502a-cab3-11e7-8903-4f898990c8bb.png)


![image](https://user-images.githubusercontent.com/7549295/32882114-90e50de2-cab3-11e7-986d-f2cdb0b861bf.png)

**Comment by BorntraegerMarc** [comment] 2017-11-16 08:52
@samiheikki is there an ETA when a new version is released? So I can test out master in our prod environment...

**Comment by BorntraegerMarc** [comment] 2017-11-17 08:15
I think it might be happening because of the actual OS as well. Check out this screenshot with `62.0.3202.94 (Official Build) (64-bit)` from browserstack.com (a windows virtual machine): 
![image](https://user-images.githubusercontent.com/7549295/32937207-ba47b576-cb77-11e7-85de-befbc0782ef2.png)

**Comment by BorntraegerMarc** [comment] 2017-11-19 14:01
@samiheikki FYI: if you are on a laptop with touch-screen then the icons are way smaller again: I think it's because the drag&drop fields are not displayed in touch-screen laptops. Also described in here: https://github.com/vaadin/vaadin-upload/issues/153

**Comment by samiheikki** [comment] 2018-03-11 09:38
@tomivirkki tested this again with IE+EDGE (master) and everything seems to be ok. I'm recommending to close this issue.

**Closed** 2018-03-13 15:14 UTC
Labels: issue, issue-backlog
