### ISSUE TITLE
Handle common error codes

### ISSUE THREAD

**Issue by rwestlund** [vaadin/vaadin-upload#164] opened 2017-04-01 02:45 UTC
At present, any 4xx error is assumed to be 403.  For example, when I return 415 because the image was in the wrong format, this element displays "Forbidden", which is incorrect.

In addition to 403, at least 400, 401, 413, and 415 are common enough to implement displaying the correct text.

**Comment by stramel** [comment] 2017-04-07 14:25
As a workaround, you may be able to specify your messages in the i18n object and use the `upload-error` event to alter which message is selected depending upon the error code.

**Comment by stramel** [comment] 2017-04-11 03:28
Similar #68

**Comment by jouni** [comment] 2017-10-23 07:12
@stramel, yeah I suppose we can. That would basically allow users to add any error codes they choose, with the corresponding error message.

**Comment by web-padawan** [comment] 2019-02-12 18:18
Closing as duplicate of #68 per above comment.

**Closed by web-padawan** 2019-02-12 18:18 UTC
