### ISSUE TITLE
animations when used with paper-dialog

### ISSUE THREAD

**Issue by davidmaxwaterman** [vaadin/vaadin-upload#186] opened 2017-05-10 06:28 UTC
This isn't, I think, a problem with vaadin-upload, but with paper-dialog.

When files are added, removed from the list, the height changes as expected and it is nicely animated. Unfortunately, when the element is within a paper-dialog, this makes it off-centre. I've added a called to this.$.dialog.fit() inside a handler for dom-change (fired by the dom-repeat inside vaadin-upload). This works, but the re-centering isn't animated and because the vaadin-upload dialog *is* animated nicely, it looks ugly. There is an issue on the paper-dialog element about this, and someone suggested a way to do this by wrapping the paper-dialog, but I had a go at implementing that solution and it's quite involved; I ultimately gave up and stuck with the ulgy jerk movement (I have actual functionality to implement so can't spend so long on animations which are only nice-to-have). I would have thought this is something that paper-dialog.fit() would do for us, perhaps even letting us set the animation. It doesn't seem like they're interested though, so I wonder if you could figure out how to wrap vaadin-upload nicely in a paper-dialog so it looks good when files are added/removed.

https://github.com/PolymerElements/paper-dialog/issues/68

**Comment by manolo** [comment] 2017-05-19 18:02
I'm unable to reproduce.

I tried this code with our latest version and didn't see the issue.

```
  <paper-dialog heading="Heading" class="scrolling" opened transition="core-transition-center">
     <vaadin-upload id="upload">
     </vaadin-upload>
  </paper-dialog>
```

[This is an animated gif](http://recordit.co/VVxNkaH0wW)  with the result adding and removing files.
Can you verify if it continues happening if you use our latest release: v2.0.0-alpha3 ?

**Comment by web-padawan** [comment] 2019-02-12 14:51
Closing per above comment and because the issue is quite outdated.

**Closed by web-padawan** 2019-02-12 14:51 UTC
