### ISSUE TITLE
disable button property

### ISSUE THREAD

**Issue by davidmaxwaterman** [vaadin/vaadin-upload#196] opened 2017-06-06 15:35 UTC
I need to prevent the user from being able to upload a file(s) until they've selected something in the UI. I couldn't see how to do this, but I saw that the paper-button would be disabled if the `maxFilesReached`. That is readonly, so I can't set that, but I figured I could set maxFiles to 0 and that seemed to disable the button.

Unfortunately, for some reason, I can still click on the disabled button and select a file. That was unexpected.

I see that the click handler isn't on the paper-button, so it being disabled is only visual. The parent div doesn't check if maxFileReached is true before activating the fileInput UI - I imagine it should do so (irrespective of my issue).

What do you think? Perhaps vaadin-upload could have a 'disabled' property that should just do the right thing, so the user doesn't have to hack it like this?

**Comment by tomivirkki** [comment] 2017-06-07 12:07
`disabled` property could be a nice addition, I recall this topic being discussed in another issue some time ago.

Anyway, being able to click the disabled add button is a regression. It seems to have occurred first in the 2.0.0-alpha1 version. Submitted a fix for it [here](https://github.com/vaadin/vaadin-upload/pull/197)

**Comment by jouni** [comment] 2017-06-07 12:52
Adding a `disabled` property is not 100% straightforward, because I don’t immediately know which parts of the UI it should affect (should it disable all buttons in the progress list as well?)

I’m planning to split this element into modular pieces in some upcoming major, where we would have something like `vaadin-file-provider` for selecting files (either dropping on it or opening the OS dialog), `vaadin-uploader` which only handles the data communication and `vaadin-upload-progress` for showing the status of files being uploaded. Then you could more easily customize the UI as well, as you could put the file selector and the progress list in separate places if needed.

**Comment by davidmaxwaterman** [comment] 2017-06-07 13:01
It would be great if it were flexible enough to derive elements from it that can be specific to particular services, eg vaadin-upload-s3, which is what I've had to develop (and fork this repo in the process).

I think also that there should be more slots, so we can add buttons before and after existing ones, rather than just replace them...well, it's a thought.

**Comment by samiheikki** [comment] 2017-06-08 05:44
Also discussed here: https://github.com/vaadin/vaadin-upload/issues/146

**Comment by web-padawan** [comment] 2019-02-12 14:53
Closing as duplicate of #146 which is still valid and should be considered as future improvement.

**Closed by web-padawan** 2019-02-12 14:53 UTC
