### ISSUE TITLE
Add listener for files removed by the user from the list

### ISSUE THREAD

**Issue by FelixGaebler** [vaadin/vaadin-upload#321] opened 2020-09-07 09:10 UTC
### Description
There is no listener for files removed from the uploaded list.
I recommend adding a `Upload#addRemoveListener` 

_U see dat? Dat needs a listener!_
![image](https://user-images.githubusercontent.com/51529181/92370506-ab9e7400-f0fa-11ea-8acb-84badff988a1.png)

**Comment by web-padawan** [comment] 2020-09-08 08:21
Closing as duplicate of https://github.com/vaadin/vaadin-upload-flow/issues/63

Workaround: https://github.com/vaadin/vaadin-upload-flow/issues/63#issuecomment-516292999

**Closed by web-padawan** 2020-09-08 08:21 UTC
