### ISSUE TITLE
Custom Drop Label Demo not working on v4.0.0-beta1

### ISSUE THREAD

**Issue by andrewspy** [vaadin/vaadin-upload#255] opened 2018-02-28 09:29 UTC
Custom Drop Label Demo not working on v4.0.0-beta1.

Link below:-

https://cdn.vaadin.com/vaadin-upload/4.0.0-beta1/demo/#upload-basic-demos

**Comment by web-padawan** [comment] 2018-02-28 09:34
Which browser are you using and what exactly is not working to you? 
Looks good in Chrome, Firefox, Safari and Edge.

**Comment by andrewspy** [comment] 2018-02-28 09:42
Using Chrome Version 64.0.3282.186 (Official Build) (64-bit) on Windows 10.

Both icon and drop label are not shown in the browser as below:-

![image](https://user-images.githubusercontent.com/3106425/36780714-bafeb284-1cae-11e8-9870-dbb1b806ad33.png)

**Comment by YuriyVaadin** [comment] 2018-03-13 08:26
Please reopen the ticket if it is still reproducible.
It would be awesome if you could provide us with demo in that case.

**Comment by andrewspy** [comment] 2018-03-13 18:26
@YuriyVaadin Using Chrome v65 (in incognito), I am still not seeing the custom label and icon. Upon further inspection on the dom element, I notice `nodrop` attribute on the "Custom Drop Label" demo, which I think it somehow wrongly detected my laptop as a mobile device and attach `nodrop` attribute to it.

I am also experiencing the same behavior with Firefox v58. However, MS Edge is working as expected.

**Comment by web-padawan** [comment] 2018-03-13 18:49
Per [MDN TouchEvent](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent) docs, it seems that this is indeed the browser detection problem, especially this line:

> As of Gecko 52.0, touch events support has been fixed and reenabled in Windows desktop platforms.

We rely on that kind of detection in other components as well, so we should definitely revisit it ASAP.

**Comment by web-padawan** [comment] 2018-03-14 07:46
@andrewspy could you please provide us with more detail about your laptop device? We probably need to have additional check for `navigator.userAgent`

**Comment by andrewspy** [comment] 2018-03-14 20:33
@web-padawan I am using Microsoft Surface Laptop running WIndows 10 Pro (Version 1709).

**Comment by platosha** [comment] 2018-03-19 09:51
Duplicate of #153. See also: #52

The idea is that most touch devices do not support drag and drop, so we intentionally disable indicating dropzone for those users to avoid confusion.

Surface is an exception, it is a drag-and-drop capable device, yet dropzone is not indicated in `<vaadin-upload>` because of having touch support enabled too. This is a long known issue of using a touch support check. At the moment, we don’t have any better, so we have to continue using that.

I’ve looked into `any-pointer` media queries, unfortunately this seems to be not any better than the current `TouchEvent`-based check. Media queries work somewhat incorrectly on Surface, this sample page reports fine pointer on Edge and coarse pointer on Chrome, regardless of whether a mouse is plugged in or not: https://googlechrome.github.io/samples/media-hover-pointer/

Meanwhile, you can workaround that issue. Set the `nodrop` property manually, for example, to have drop label always enabled:

```javascript
upload.nodrop = false;
```

**Closed by platosha** 2018-03-19 09:51 UTC
Labels: bug, in progress, needs research
